version: '3'
services:
  app:
    image: go_image:mine
    container_name: go_container
    build:
      context: .
      dockerfile: Dockerfile
    tty: true 
    volumes:
      - C:\Users\Owner\git:/go/src/work 